### ISSUE TITLE
Find a simple way to pass and parse Args

### ISSUE THREAD

**Issue by insanitybit** [insanitybit/Cricket#10]
Rather than sending a raw vector of strings for command line args there should be a more ergonomic way using something like an argparser.

**Comment by BurntSushi** [comment]
I think the three most popular choices at the moment are:
1. [clap](https://crates.io/crates/clap)
2. [docopt](https://crates.io/crates/docopt)
3. [getopts](https://crates.io/crates/getopts)

**Comment by insanitybit** [comment]
Nice, those might work. It needs to be able to store the args properly, and then send them across the network to the fuzzer where they'll actually be used. Right now I'm just using a vector of strings, but an argparser that can handle defaults, etc, like those, will hopefully streamline it. Thanks.

**Comment by insanitybit** [comment]
I've decided to handle this entirely on the fuzzer side rather than the master. There's really no need for these arguments to ever change except in very specific cases where the fuzzer is most capable of handling them. See: https://github.com/insanitybit/Cricket/issues/12
